services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    networks:
      - production
    restart: always

networks:
  production:
