services:
    laravel:
        image: ${APP_NAME}:${TAG:-latest}
        build:
            context: ../../
            dockerfile: ./docker/production/Dockerfile
        env_file:
            - .env
        networks:
            - production
        restart: unless-stopped
        depends_on:
            redis:
                condition: service_healthy
            mariadb:
                condition: service_healthy
        healthcheck:
            test:
                - CMD
                - curl
                - http://localhost:9000/api/check-health
            interval: 10s
            retries: 10
            start_period: 30s
            timeout: 10s
        volumes:
            - ./logs:/var/www/html/storage/logs
            - ./start.sh:/var/www/html/start.sh
    schedule:
        image: ${APP_NAME}:${TAG:-latest}
        build:
            context: ../../
            dockerfile: ./docker/production/Dockerfile
        env_file:
            - .env
        networks:
            - production
        restart: unless-stopped
        depends_on:
            laravel:
                condition: service_healthy
        command: [
            'php', '/var/www/html/artisan', 'schedule:work'
        ]
        volumes:
            - ./logs-schedule:/var/www/html/storage/logs
    nginx:
        container_name: ${APP_DOMAIN:-nginx}
        image: nginx:alpine3.20
        privileged: true
        volumes:
            - nginx_data:/etc/nginx
            - nginx_log:/var/log/nginx
            - ../production/conf.d:/etc/nginx/conf.d
        env_file:
            - .env
        ports:
            - 80:80
            - 443:443
        networks:
            - production
        restart: unless-stopped
        depends_on:
            laravel:
                condition: service_healthy
        healthcheck:
            test:
                - CMD
                - curl
                - http://localhost
            interval: 10s
            retries: 10
            start_period: 60s
            timeout: 10s
    mariadb:
        image: mariadb:11.4.3
        env_file:
            - .env
        networks:
            - production
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        restart: unless-stopped
    redis:
        image: redis:7.4.1-alpine
        env_file:
            - .env
        command: redis-server --save "" --appendonly no
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: unless-stopped
        networks:
            - production

networks:
    production:

volumes:
    db:
        driver: local
    nginx_data:
    nginx_log:
